#!/usr/bin/env node
/**
 * One-time project setup: `npm run setup`
 *
 * Safe to run again at any time: it never overwrites existing secrets and
 * migrations/seed are idempotent.
 *
 *   1. Checks Node.js and npm versions.
 *   2. Installs dependencies (npm install).
 *   3. Creates apps/api/.dev.vars from .dev.vars.example, generating random
 *      values for every "generate-me" placeholder. Existing values are kept.
 *   4. Creates the local D1 database and applies all migrations.
 *   5. Loads development seed data.
 */
import { execSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const MIN_NODE = [20, 19, 0];

const c = {
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
};

function step(n, text) {
  console.log(`\n${c.bold(`[${n}/5]`)} ${text}`);
}

function run(cmd, opts = {}) {
  console.log(c.dim(`  $ ${cmd}`));
  execSync(cmd, { cwd: root, stdio: 'inherit', ...opts });
}

function fail(message) {
  console.error(`\n${c.red('✖ Setup failed:')} ${message}`);
  process.exit(1);
}

// ── 1. Versions ──────────────────────────────────────────────────────────────
step(1, 'Checking tool versions');
const nodeVersion = process.versions.node.split('.').map(Number);
const nodeOk =
  nodeVersion[0] > MIN_NODE[0] ||
  (nodeVersion[0] === MIN_NODE[0] &&
    (nodeVersion[1] > MIN_NODE[1] ||
      (nodeVersion[1] === MIN_NODE[1] && nodeVersion[2] >= MIN_NODE[2])));
if (!nodeOk) {
  fail(`Node.js ${MIN_NODE.join('.')} or newer is required (you have ${process.versions.node}).
  Install the current LTS from https://nodejs.org and run \`npm run setup\` again.`);
}
const npmVersion = execSync('npm --version', { encoding: 'utf8' }).trim();
if (Number(npmVersion.split('.')[0]) < 10) {
  fail(`npm 10 or newer is required (you have ${npmVersion}). Run: npm install -g npm@latest`);
}
console.log(c.green(`  ✔ Node ${process.versions.node}, npm ${npmVersion}`));

// ── 2. Dependencies ──────────────────────────────────────────────────────────
step(2, 'Installing dependencies (this can take a few minutes the first time)');
try {
  run('npm install --no-fund --no-audit');
} catch {
  fail(`npm install failed. See the error above.
  If it mentions "edgesOut", run \`npx npm@11 install\` instead, then \`npm run setup\` again.`);
}

// ── 3. Local secrets ─────────────────────────────────────────────────────────
step(3, 'Creating local secrets (apps/api/.dev.vars)');
const examplePath = join(root, 'apps/api/.dev.vars.example');
const varsPath = join(root, 'apps/api/.dev.vars');

const parse = (text) =>
  Object.fromEntries(
    text
      .split(/\r?\n/)
      .filter((line) => line.trim() && !line.trim().startsWith('#') && line.includes('='))
      .map((line) => {
        const i = line.indexOf('=');
        return [line.slice(0, i).trim(), line.slice(i + 1).trim()];
      }),
  );

const example = parse(readFileSync(examplePath, 'utf8'));
const existing = existsSync(varsPath) ? parse(readFileSync(varsPath, 'utf8')) : {};
const added = [];
for (const [key, value] of Object.entries(example)) {
  if (existing[key] !== undefined) continue;
  existing[key] = value === 'generate-me' ? randomBytes(32).toString('hex') : value;
  added.push(key);
}
const header =
  '# Local secrets for the API Worker. Generated by `npm run setup`.\n' +
  '# NEVER commit this file. See .dev.vars.example for what each value means.\n';
writeFileSync(
  varsPath,
  header +
    Object.entries(existing)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') +
    '\n',
);
console.log(
  added.length
    ? c.green(`  ✔ Added: ${added.join(', ')}`)
    : c.green('  ✔ All secrets already present (kept as they are)'),
);

// ── 4. Database ──────────────────────────────────────────────────────────────
step(4, 'Creating the local database and applying migrations');
// CI=true makes wrangler skip its "apply these migrations?" confirmation prompt.
const nonInteractive = { env: { ...process.env, CI: 'true' } };
try {
  run('npm run db:migrate:local', nonInteractive);
} catch {
  fail('Applying migrations failed. See the error above.');
}

// ── 5. Seed ──────────────────────────────────────────────────────────────────
step(5, 'Loading development seed data');
try {
  run('npm run db:seed', nonInteractive);
} catch {
  fail('Seeding failed. See the error above.');
}

console.log(`
${c.green(c.bold('✔ SkillVerse is ready.'))}

  Start everything:   ${c.bold('npm run dev')}
  Website:            http://localhost:5173
  API health:         http://localhost:5173/api/health
  API docs:           http://localhost:8787/api/docs
  Browse database:    ${c.bold('npm run db:studio')}

  New here? Read README.md → "Your first contribution".
`);
